import rose from "./images/rose.jpg"

export const data = [

    {
        id:1,
        name: 'Oleander flower or Arali flower',
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"pick",
        quantity:'50kg to 500kg ',
        category: 'popular',
        image: 'https://5.imimg.com/data5/SELLER/Default/2021/11/NH/EB/HC/53855503/webp-net-resizeimage-2021-11-01t143954-101-500x500.jpg',
    },
    {
        id:2,
        name: 'Big Nandiyavattai Flower',
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"white",
        quantity:'50kg to 500kg',
        category: 'popular', 
        image:'https://5.imimg.com/data5/SELLER/Default/2020/8/XK/NB/AB/4621023/3-500x500.jpg'
    },
    {
        id:3,
        name: 'Edouard Rose or Paneer Rose',
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"pick",
        quantity:'10kg to 200kg',
        category: 'popular', 
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Rose%2C_Sir_Edward_Elgar%2C_%E3%83%90%E3%83%A9%2C_%E3%82%B5%E3%83%BC_%E3%82%A8%E3%83%89%E3%83%AF%E3%83%BC%E3%83%89_%E3%82%A8%E3%83%AB%E3%82%AC%E3%83%BC%2C_%2814503657064%29.jpg/1200px-Rose%2C_Sir_Edward_Elgar%2C_%E3%83%90%E3%83%A9%2C_%E3%82%B5%E3%83%BC_%E3%82%A8%E3%83%89%E3%83%AF%E3%83%BC%E3%83%89_%E3%82%A8%E3%83%AB%E3%82%AC%E3%83%BC%2C_%2814503657064%29.jpg?20150914190514'
    }
]

export const dataTwo = [
    {
        id:1,
        name: ' Oleander Flower or Arali Flower',
        price: 145,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"pick",
        quantity:'50kg to 500kg ',
        category: 'popular', 
        image: ['https://5.imimg.com/data5/SELLER/Default/2021/11/NH/EB/HC/53855503/webp-net-resizeimage-2021-11-01t143954-101-500x500.jpg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz). Высота букета 90-110 см'
    },
    {
        id:2,
        name: ' White Oleander Flower  or white Arali Flower',
        price: 8100.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"white",
        quantity:'20kg',
        category: 'mix', 
        image: ['https://5.imimg.com/data5/ANDROID/Default/2023/1/TT/IT/UW/130478539/product-jpeg-500x500.jpg'],
        showMore: false,
        description: 'Состав: Хризантема (сорт Delano). Высота букета 70-90 см'
    },
    {
        id:3,
        name: 'Red Oleander Flower or Red Arali Flower',
        price: 11000.00, 
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"red",
        quantity:'50kg',
        category: 'mix', 
        image: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHvJLca_PIdfd92CPSOqps1K5YG1N_Ldgpfw&usqp=CAU'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:4,
        name: 'yellow Oleander flower or Yellow Arali Flower ',
        price: 5500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"yellow",
        quantity:'20kg',
        category: 'mix', 
        image: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMc2_poooT4cXpFx3BaiC2TaJRcFWl7gfK9Q&usqp=CAU'],
        showMore: false,
        description: 'Состав: Ромашка (сорт Мэй Куин). Высота букета 50-70 см' 
    },
    {
        id:5,
        name: 'Hybrid Oleander flower or Hybrid Arali flower ',
        price: 7500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"Hybrid Arali",
        quantity:'50kg to 200',
        category: 'popular', 
        image: ['https://m.media-amazon.com/images/I/51mfgan47bL._AC_UF350,350_QL80_.jpg'],
        showMore: false,
        description: 'Состав: Антуриум' 
    },
    {
        id:6,
        name: 'Big nandiyavattai flower',
        price: 10300.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"white",
        quantity:'50kg to 500kg',
        category: 'popular', 
        image: ['https://5.imimg.com/data5/SELLER/Default/2020/8/XK/NB/AB/4621023/3-500x500.jpg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:7,
        name: 'small nandiyavattai flower',
        price: 5500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"white",
        quantity:'5kg to 10kg',
        category: 'mix', 
        image: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLytD_zgLy15frTGY-VX-2y0CMdWoC1sucw0lMZZenOqm4b3asH7_fB0ydX7vZehxvPSY&usqp=CAU'],
        showMore: false,
        description: 'Состав: Гомфрена, Нигелла, Физалис' 
    },
    {
        id:8,
        name: 'edouard rose or Paneer rose',
        price: 187,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"pick",
        quantity:'10kg to 200kg',
        category: 'dried', 
        image: ['https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Rose%2C_Sir_Edward_Elgar%2C_%E3%83%90%E3%83%A9%2C_%E3%82%B5%E3%83%BC_%E3%82%A8%E3%83%89%E3%83%AF%E3%83%BC%E3%83%89_%E3%82%A8%E3%83%AB%E3%82%AC%E3%83%BC%2C_%2814503657064%29.jpg/1200px-Rose%2C_Sir_Edward_Elgar%2C_%E3%83%90%E3%83%A9%2C_%E3%82%B5%E3%83%BC_%E3%82%A8%E3%83%89%E3%83%AF%E3%83%BC%E3%83%89_%E3%82%A8%E3%83%AB%E3%82%AC%E3%83%BC%2C_%2814503657064%29.jpg?20150914190514'],
        showMore: false,
        description: 'Состав: Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:9,
        name: 'andhra  rose or andhra  rose',
        price: 45,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"pick",
        quantity:'10kg to 50kg',
        category: 'popular', 
        image: ['https://4.imimg.com/data4/XP/IS/IMOB-58341007/img_20180529_104115-jpg-250x250.jpg'],
        showMore: false,
        description: 'Состав: Ромашка (сорт Мэй Куин). Высота букета 50-70 см' 
    },
    {
        id:10,
        name: 'michelia champaca flower or shenbaga',
        price: 2,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"Yellow and white",
        quantity:'50flower to 1000flower',
        category: 'popular', 
        image: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSpn6O0dNMPJfSEf7oazkMPvu4_pMTJp546A&usqp=CAU'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:11,
        name: 'manoranjitham flower',
        price: 2,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"green",
        quantity:'50 to 100',
        category: 'mix', 
        image:['https://reemzbasket.com/cart/product/web/product/73.jpg'],
        showMore: false,
        description: 'Состав: Хризантема (сорт Delano). Высота букета 70-90 см' 
    },
    {
        id:12,
        name: 'marigold yellow  ',
        price: 12500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"yellow",
        quantity:'25kg to 100kg ',
        category: 'popular', 
        image: ['https://m.media-amazon.com/images/I/413PrkUhopL.jpg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:13,
        name: 'marigold orange ',
        price: 1500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"orange",
        quantity:'25kg to 200kg',
        category: 'popular', 
        image: ['https://mybageecha.com/cdn/shop/products/Marigold_Garland_Orange_600x600_crop_center.jpg?v=1571438547'],
        showMore: false,
        description: 'Состав: Цикламен' 
    },
    {
        id:14,
        name: 'Hybrid small Pinwheel or Nandiawatta',
        price: 10500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"white",
        quantity:'3kg',
        category: 'mix', 
        image: ['https://all-mongolia.ru/wp-content/uploads/1/c/9/1c9895651c193b33c53be4582941aacd.jpeg'],
        showMore: false,
        description: 'Состав: Хризантема (сорт Delano). Высота букета 70-90 см' 
    },
    {
        id:15,
        name: 'december flower',
        price: 17500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY..',
        color:"",
        quantity:'5kg to 50kg',
        category: 'roses', 
        image: ['https://i.pinimg.com/236x/ba/e1/3f/bae13f8f06b9318b585d2ae7d13bb36f--shade-plants-perennial-ground-cover-plants.jpg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz). Высота букета 90-110 см' 
    },
    {
        id:16,
        name: 'Hybiscus flower',
        price: 15200.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"red",
        quantity:'100 to 1000',
        category: 'dried', 
        image: ['https://wildflowerplantstation.com/wp-content/uploads/2021/06/Desi-Hibiscus-Flower.jpg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:17,
        name: 'Kanakambaram flower',
        price: 18500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"",
        quantity:'5kg to 20kg',
        category: 'roses', 
        image: ['https://i.pinimg.com/564x/ed/0d/8a/ed0d8a13045ed498155e8d7bf5253e94.jpg' ],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:18,
        name: 'Jasmine(Malligai)',
        price: 4500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"white",
        quantity:'5kg to 20kg',
        category: 'roses', 
        image: ['https://i.pinimg.com/736x/23/5c/dd/235cdda93a4fa557424e7a357525e814.jpg'],
        showMore: false,
        description: 'Состав: Хризантема (сорт Delano). Высота букета 70-90 см' 
    },
    {
        id:19,
        name: 'Sampangi Flower',
        price: 3700.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"white",
        quantity:'5kg to 50kg',
        category: 'roses', 
        image: ['https://img2.exportersindia.com/product_images/bc-small/2023/1/10028014/sampangi-flower-1673426229-6714050.jpeg'],
        showMore: false,
        description: 'Состав: Ромашка (сорт Мэй Куин). Высота букета 50-70 см' 
    },
    {
        id:20,
        name: 'Kozhi Kondai Flower',
        price: 14500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"red",
        quantity:'25kg to 200kg',
        category: 'mix', 
        image: ['https://i.pinimg.com/564x/fa/48/0c/fa480cd9f5ae50e045e7efe77dc72d40.jpg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:21,
        name: 'Vada Malli flower',
        price: 14500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"",
        quantity:'5kg to 50kg',
        category: 'mix', 
        image: ['https://4.imimg.com/data4/HT/SO/MY-10480455/vadamalli-flower-500x500.jpg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:22,
        name: 'button rose',
        price: 14500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"red",
        quantity:'5kg to 100kg',
        category: 'popular', 
        image: ['https://5.imimg.com/data5/SELLER/Default/2022/10/ES/YC/DR/161706854/red-button-rose-merrable-2-.jpeg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:23,
        name: 'colour jasmine',
        price: 14500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"colour",
        quantity:'10kg to 30kg',
        category: 'mix', 
        image: ['https://www.santhionlineplants.com/wp-content/uploads/2021/11/Stare-Jasmine-Color-Kagattan-1.jpg'],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },
    {
        id:24,
        name: 'colour jasmine',
        price: 14500.00,
        area:'DELIVERY AVAILABLE TO ALL OVER TAMILNADU AND ALSO WHOLE INDIA THROUGH TRANSPORT FACILITY.',
        color:"colour",
        quantity:'10kg to 30kg',
        category: 'mix', 
        image: ["https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR8slShbfKdQg7KueKx88_kwAvhboaosWNtk1MPoqhdG9BOdvXA"],
        showMore: false,
        description: 'Состав: Роза (сорт Flammentanz), Роза (сорт Jacques Cartier), Лилия,  Берграс' 
    },

]